steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - 'docker pull gcr.io/gain-data/gcp-storage-emulator:latest || exit 0'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/gain-data/gcp-storage-emulator:$_COMMIT_SHA'
      - '-t'
      - 'gcr.io/gain-data/gcp-storage-emulator:latest'
      - '--cache-from'
      - 'gcr.io/gain-data/gcp-storage-emulator:latest'
      - '.'
images:
  - 'gcr.io/gain-data/gcp-storage-emulator:$_COMMIT_SHA'
  - 'gcr.io/gain-data/gcp-storage-emulator:latest'
