name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            requirements.lock
            requirements-dev.lock

      - name: Install dependencies
        run: |
          PYTHONDONTWRITEBYTECODE=1 pip install -r requirements.lock
          PYTHONDONTWRITEBYTECODE=1 pip install -r requirements-dev.lock

      # FORK: This is duplicated from the flake used by the source repo
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest
